# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [15]:
arr1 = np.ones((10))
print(arr1)

arr2 = np.arange(1,21,1, dtype="int")
print(arr2)

arr3 = np.ones((5,5))
print(arr3)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [20]:
arr4 = np.random.rand(3,3,3)
print(arr4)

arr4a = arr4.reshape(27)
print(arr4a)

[[[0.00615033 0.18194866 0.31722059]
  [0.23060117 0.47563122 0.03068173]
  [0.17140573 0.89964822 0.92735294]]

 [[0.48749939 0.24257943 0.73695367]
  [0.39934863 0.9153326  0.29400673]
  [0.53930684 0.21380483 0.3547604 ]]

 [[0.50226639 0.47679678 0.51592478]
  [0.28861718 0.23361802 0.27227273]
  [0.86682621 0.5545918  0.7930053 ]]]
[0.00615033 0.18194866 0.31722059 0.23060117 0.47563122 0.03068173
 0.17140573 0.89964822 0.92735294 0.48749939 0.24257943 0.73695367
 0.39934863 0.9153326  0.29400673 0.53930684 0.21380483 0.3547604
 0.50226639 0.47679678 0.51592478 0.28861718 0.23361802 0.27227273
 0.86682621 0.5545918  0.7930053 ]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [59]:
arr5 = np.linspace(0.5,10,20)
print(arr5)

[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [87]:
import numpy as np
a = np.arange(1, 26).reshape(5,-1)

In [ ]:
20

In [88]:
print("Original Array")
print(a)
print("Output of 20")
print(a[3,4])

Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Output of 20
20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [44]:
print(a[1:,3:]) 

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [73]:
print(a[1,0:])

[ 6  7  8  9 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [60]:
print(np.sum(a))

325


## 2.6 

Calculate the sum of each row in `a`.

In [81]:
print(np.sum(a[0]))
print(np.sum(a[1,0:]))
print(np.sum(a[2,0:]))
print(np.sum(a[3,0:]))
print(np.sum(a[4,0:]))


15
40
65
90
115


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [90]:
meana = np.sum(a)/25
print(meana)

abool = a > 150
print(abool)

13.0
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [ ]:
# Codes comes here

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [ ]:
# Code comes here

## 2.10 

How many rows and columns are there in the dataframe?

In [ ]:
#Code comes here

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [ ]:
# Code comes here

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [ ]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.