# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [93]:
arr1 = np.ones((10))
print(arr1)

arr2 = np.arange(1,21,1, dtype="int")
print(arr2)

arr3 = np.ones((5,5), dtype="int")
print(arr3)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [20]:
arr4 = np.random.rand(3,3,3)
print(arr4)

arr4a = arr4.reshape(27)
print(arr4a)

[[[0.00615033 0.18194866 0.31722059]
  [0.23060117 0.47563122 0.03068173]
  [0.17140573 0.89964822 0.92735294]]

 [[0.48749939 0.24257943 0.73695367]
  [0.39934863 0.9153326  0.29400673]
  [0.53930684 0.21380483 0.3547604 ]]

 [[0.50226639 0.47679678 0.51592478]
  [0.28861718 0.23361802 0.27227273]
  [0.86682621 0.5545918  0.7930053 ]]]
[0.00615033 0.18194866 0.31722059 0.23060117 0.47563122 0.03068173
 0.17140573 0.89964822 0.92735294 0.48749939 0.24257943 0.73695367
 0.39934863 0.9153326  0.29400673 0.53930684 0.21380483 0.3547604
 0.50226639 0.47679678 0.51592478 0.28861718 0.23361802 0.27227273
 0.86682621 0.5545918  0.7930053 ]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [59]:
arr5 = np.linspace(0.5,10,20)
print(arr5)

[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [87]:
import numpy as np
a = np.arange(1, 26).reshape(5,-1)

In [ ]:
20

In [88]:
print("Original Array")
print(a)
print("Output of 20")
print(a[3,4])

Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Output of 20
20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [44]:
print(a[1:,3:]) 

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [73]:
print(a[1,0:])

[ 6  7  8  9 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [60]:
print(np.sum(a))

325


## 2.6 

Calculate the sum of each row in `a`.

In [81]:
print(np.sum(a[0]))
print(np.sum(a[1,0:]))
print(np.sum(a[2,0:]))
print(np.sum(a[3,0:]))
print(np.sum(a[4,0:]))


15
40
65
90
115


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [91]:
meana = np.sum(a)/25
print(meana)

abool = a > 13
print(abool)

13.0
[[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [94]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [106]:
country_df = pd.read_csv("data/food_consumption.csv", header=0)
country_df.head(10)

country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.10 

How many rows and columns are there in the dataframe?

In [109]:
print(country_df.describe)
#1430 rows, 4 columns

<bound method NDFrame.describe of          country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]>


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [116]:
co2Mn = country_df["co2_emmission"].mean()
print (co2Mn)
#74.383993006993

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [123]:
co2_stats = pd.DataFrame()
co2_stats ["country"] = country_df.groupby("co2_emmission")['country'].max()  
co2_stats ["food_category"] = country_df.groupby("co2_emmission")['food_category'].max()
co2_stats

#Argentina - Beef

country food_category
co2_emmission                                    
0.00                      Venezuela      Soybeans
0.01                        Ukraine      Soybeans
0.02                 United Kingdom      Soybeans
0.03                         Poland      Soybeans
0.04           United Arab Emirates      Soybeans
...                             ...           ...
1022.94                     Bermuda          Beef
1044.85                   Australia          Beef
1118.29                         USA          Beef
1211.17                      Brazil          Beef
1712.00                   Argentina          Beef

[1183 rows x 2 columns]

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [127]:
highemission_df = country_df.query('co2_emmission > 1000')
highemission_df

#5 countries

country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94

## 2.14

Which country consumes the least amount of beef per person per year?


In [144]:
justbeef = country_df[country_df["food_category"]=="Beef"]
beefMin = justbeef.groupby("consumption")['country'].min()
beefMin

#Liberia

consumption
0.78        Liberia
0.81          India
1.04     Mozambique
1.09          Ghana
1.28     Bangladesh
            ...    
33.15       Bermuda
33.86     Australia
36.24           USA
39.25        Brazil
55.48     Argentina
Name: country, Length: 125, dtype: object

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [154]:
meat_query = country_df.query('food_category=="Pork"' and 'food_category=="Poultry"' and'food_category=="Fish"' and 'food_category=="Lamb"' and 'food_category=="Goat"' and 'food_category=="Beef"')
meat_query.to_csv("data/meat_data.csv", sep=",", header=True)

meat_df = pd.read_csv("data/meat_data.csv", header=0)
meattotal = meat_df["co2_emmission"].sum()
meattotal

#48633.259999999995

48633.259999999995

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [161]:
nonmeat_query = country_df.query('food_category=="Eggs"' and 'food_category=="Milk - inc. cheese"' and'food_category=="Wheat and Wheat Products"' and 'food_category=="Rice"' and 'food_category=="Soybeans"' and 'food_category=="Nuts inc. Peanut Butter"')
nonmeat_query.to_csv("data/nonmeat_data.csv", sep=",", header=True)


nonmeat_df = pd.read_csv("data/nonmeat_data.csv", header=0)
nonmeattotal = nonmeat_df["co2_emmission"].sum()
nonmeattotal

#951.99

951.99

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.